/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PanelImport } from './routes/_panel'
import { Route as IndexImport } from './routes/index'
import { Route as PanelProcessingsImport } from './routes/_panel/_processings'

// Create Virtual Routes

const AuthSignInLazyImport = createFileRoute('/auth/sign-in')()
const PanelProcessingsIndexLazyImport = createFileRoute(
  '/_panel/processings/',
)()
const PanelProcessingsProcessingsIdUploadLazyImport = createFileRoute(
  '/_panel/_processings/processings/$id/upload',
)()
const PanelProcessingsProcessingsIdGraphLazyImport = createFileRoute(
  '/_panel/_processings/processings/$id/graph',
)()
const PanelProcessingsProcessingsIdForecastLazyImport = createFileRoute(
  '/_panel/_processings/processings/$id/forecast',
)()
const PanelProcessingsProcessingsIdDistributionLazyImport = createFileRoute(
  '/_panel/_processings/processings/$id/distribution',
)()

// Create/Update Routes

const PanelRoute = PanelImport.update({
  id: '/_panel',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInLazyRoute = AuthSignInLazyImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/sign-in.lazy').then((d) => d.Route))

const PanelProcessingsRoute = PanelProcessingsImport.update({
  id: '/_processings',
  getParentRoute: () => PanelRoute,
} as any)

const PanelProcessingsIndexLazyRoute = PanelProcessingsIndexLazyImport.update({
  path: '/processings/',
  getParentRoute: () => PanelRoute,
} as any).lazy(() =>
  import('./routes/_panel/processings/index.lazy').then((d) => d.Route),
)

const PanelProcessingsProcessingsIdUploadLazyRoute =
  PanelProcessingsProcessingsIdUploadLazyImport.update({
    path: '/processings/$id/upload',
    getParentRoute: () => PanelProcessingsRoute,
  } as any).lazy(() =>
    import('./routes/_panel/_processings/processings/$id/upload.lazy').then(
      (d) => d.Route,
    ),
  )

const PanelProcessingsProcessingsIdGraphLazyRoute =
  PanelProcessingsProcessingsIdGraphLazyImport.update({
    path: '/processings/$id/graph',
    getParentRoute: () => PanelProcessingsRoute,
  } as any).lazy(() =>
    import('./routes/_panel/_processings/processings/$id/graph.lazy').then(
      (d) => d.Route,
    ),
  )

const PanelProcessingsProcessingsIdForecastLazyRoute =
  PanelProcessingsProcessingsIdForecastLazyImport.update({
    path: '/processings/$id/forecast',
    getParentRoute: () => PanelProcessingsRoute,
  } as any).lazy(() =>
    import('./routes/_panel/_processings/processings/$id/forecast.lazy').then(
      (d) => d.Route,
    ),
  )

const PanelProcessingsProcessingsIdDistributionLazyRoute =
  PanelProcessingsProcessingsIdDistributionLazyImport.update({
    path: '/processings/$id/distribution',
    getParentRoute: () => PanelProcessingsRoute,
  } as any).lazy(() =>
    import(
      './routes/_panel/_processings/processings/$id/distribution.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PanelImport
      parentRoute: typeof rootRoute
    }
    '/_panel/_processings': {
      id: '/_panel/_processings'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PanelProcessingsImport
      parentRoute: typeof PanelImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInLazyImport
      parentRoute: typeof rootRoute
    }
    '/_panel/processings/': {
      id: '/_panel/processings/'
      path: '/processings'
      fullPath: '/processings'
      preLoaderRoute: typeof PanelProcessingsIndexLazyImport
      parentRoute: typeof PanelImport
    }
    '/_panel/_processings/processings/$id/distribution': {
      id: '/_panel/_processings/processings/$id/distribution'
      path: '/processings/$id/distribution'
      fullPath: '/processings/$id/distribution'
      preLoaderRoute: typeof PanelProcessingsProcessingsIdDistributionLazyImport
      parentRoute: typeof PanelProcessingsImport
    }
    '/_panel/_processings/processings/$id/forecast': {
      id: '/_panel/_processings/processings/$id/forecast'
      path: '/processings/$id/forecast'
      fullPath: '/processings/$id/forecast'
      preLoaderRoute: typeof PanelProcessingsProcessingsIdForecastLazyImport
      parentRoute: typeof PanelProcessingsImport
    }
    '/_panel/_processings/processings/$id/graph': {
      id: '/_panel/_processings/processings/$id/graph'
      path: '/processings/$id/graph'
      fullPath: '/processings/$id/graph'
      preLoaderRoute: typeof PanelProcessingsProcessingsIdGraphLazyImport
      parentRoute: typeof PanelProcessingsImport
    }
    '/_panel/_processings/processings/$id/upload': {
      id: '/_panel/_processings/processings/$id/upload'
      path: '/processings/$id/upload'
      fullPath: '/processings/$id/upload'
      preLoaderRoute: typeof PanelProcessingsProcessingsIdUploadLazyImport
      parentRoute: typeof PanelProcessingsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PanelRoute: PanelRoute.addChildren({
    PanelProcessingsRoute: PanelProcessingsRoute.addChildren({
      PanelProcessingsProcessingsIdDistributionLazyRoute,
      PanelProcessingsProcessingsIdForecastLazyRoute,
      PanelProcessingsProcessingsIdGraphLazyRoute,
      PanelProcessingsProcessingsIdUploadLazyRoute,
    }),
    PanelProcessingsIndexLazyRoute,
  }),
  AuthSignInLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_panel",
        "/auth/sign-in"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_panel": {
      "filePath": "_panel.tsx",
      "children": [
        "/_panel/_processings",
        "/_panel/processings/"
      ]
    },
    "/_panel/_processings": {
      "filePath": "_panel/_processings.tsx",
      "parent": "/_panel",
      "children": [
        "/_panel/_processings/processings/$id/distribution",
        "/_panel/_processings/processings/$id/forecast",
        "/_panel/_processings/processings/$id/graph",
        "/_panel/_processings/processings/$id/upload"
      ]
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.lazy.tsx"
    },
    "/_panel/processings/": {
      "filePath": "_panel/processings/index.lazy.tsx",
      "parent": "/_panel"
    },
    "/_panel/_processings/processings/$id/distribution": {
      "filePath": "_panel/_processings/processings/$id/distribution.lazy.tsx",
      "parent": "/_panel/_processings"
    },
    "/_panel/_processings/processings/$id/forecast": {
      "filePath": "_panel/_processings/processings/$id/forecast.lazy.tsx",
      "parent": "/_panel/_processings"
    },
    "/_panel/_processings/processings/$id/graph": {
      "filePath": "_panel/_processings/processings/$id/graph.lazy.tsx",
      "parent": "/_panel/_processings"
    },
    "/_panel/_processings/processings/$id/upload": {
      "filePath": "_panel/_processings/processings/$id/upload.lazy.tsx",
      "parent": "/_panel/_processings"
    }
  }
}
ROUTE_MANIFEST_END */
