/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PanelImport } from './routes/_panel'
import { Route as IndexImport } from './routes/index'
import { Route as PanelProcessingsIdProcessingsImport } from './routes/_panel/processings/$id/_processings'

// Create Virtual Routes

const AuthSignInLazyImport = createFileRoute('/auth/sign-in')()
const PanelProcessingsIdImport = createFileRoute('/_panel/processings/$id')()
const PanelProcessingsIndexLazyImport = createFileRoute(
  '/_panel/processings/',
)()
const PanelProcessingsIdProcessingsUploadLazyImport = createFileRoute(
  '/_panel/processings/$id/_processings/upload',
)()
const PanelProcessingsIdProcessingsGraphLazyImport = createFileRoute(
  '/_panel/processings/$id/_processings/graph',
)()
const PanelProcessingsIdProcessingsForecastLazyImport = createFileRoute(
  '/_panel/processings/$id/_processings/forecast',
)()
const PanelProcessingsIdProcessingsDistributionLazyImport = createFileRoute(
  '/_panel/processings/$id/_processings/distribution',
)()

// Create/Update Routes

const PanelRoute = PanelImport.update({
  id: '/_panel',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInLazyRoute = AuthSignInLazyImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/sign-in.lazy').then((d) => d.Route))

const PanelProcessingsIdRoute = PanelProcessingsIdImport.update({
  path: '/processings/$id',
  getParentRoute: () => PanelRoute,
} as any)

const PanelProcessingsIndexLazyRoute = PanelProcessingsIndexLazyImport.update({
  path: '/processings/',
  getParentRoute: () => PanelRoute,
} as any).lazy(() =>
  import('./routes/_panel/processings/index.lazy').then((d) => d.Route),
)

const PanelProcessingsIdProcessingsRoute =
  PanelProcessingsIdProcessingsImport.update({
    id: '/_processings',
    getParentRoute: () => PanelProcessingsIdRoute,
  } as any)

const PanelProcessingsIdProcessingsUploadLazyRoute =
  PanelProcessingsIdProcessingsUploadLazyImport.update({
    path: '/upload',
    getParentRoute: () => PanelProcessingsIdProcessingsRoute,
  } as any).lazy(() =>
    import('./routes/_panel/processings/$id/_processings/upload.lazy').then(
      (d) => d.Route,
    ),
  )

const PanelProcessingsIdProcessingsGraphLazyRoute =
  PanelProcessingsIdProcessingsGraphLazyImport.update({
    path: '/graph',
    getParentRoute: () => PanelProcessingsIdProcessingsRoute,
  } as any).lazy(() =>
    import('./routes/_panel/processings/$id/_processings/graph.lazy').then(
      (d) => d.Route,
    ),
  )

const PanelProcessingsIdProcessingsForecastLazyRoute =
  PanelProcessingsIdProcessingsForecastLazyImport.update({
    path: '/forecast',
    getParentRoute: () => PanelProcessingsIdProcessingsRoute,
  } as any).lazy(() =>
    import('./routes/_panel/processings/$id/_processings/forecast.lazy').then(
      (d) => d.Route,
    ),
  )

const PanelProcessingsIdProcessingsDistributionLazyRoute =
  PanelProcessingsIdProcessingsDistributionLazyImport.update({
    path: '/distribution',
    getParentRoute: () => PanelProcessingsIdProcessingsRoute,
  } as any).lazy(() =>
    import(
      './routes/_panel/processings/$id/_processings/distribution.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PanelImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInLazyImport
      parentRoute: typeof rootRoute
    }
    '/_panel/processings/': {
      id: '/_panel/processings/'
      path: '/processings'
      fullPath: '/processings'
      preLoaderRoute: typeof PanelProcessingsIndexLazyImport
      parentRoute: typeof PanelImport
    }
    '/_panel/processings/$id': {
      id: '/_panel/processings/$id'
      path: '/processings/$id'
      fullPath: '/processings/$id'
      preLoaderRoute: typeof PanelProcessingsIdImport
      parentRoute: typeof PanelImport
    }
    '/_panel/processings/$id/_processings': {
      id: '/_panel/processings/$id/_processings'
      path: '/processings/$id'
      fullPath: '/processings/$id'
      preLoaderRoute: typeof PanelProcessingsIdProcessingsImport
      parentRoute: typeof PanelProcessingsIdRoute
    }
    '/_panel/processings/$id/_processings/distribution': {
      id: '/_panel/processings/$id/_processings/distribution'
      path: '/distribution'
      fullPath: '/processings/$id/distribution'
      preLoaderRoute: typeof PanelProcessingsIdProcessingsDistributionLazyImport
      parentRoute: typeof PanelProcessingsIdProcessingsImport
    }
    '/_panel/processings/$id/_processings/forecast': {
      id: '/_panel/processings/$id/_processings/forecast'
      path: '/forecast'
      fullPath: '/processings/$id/forecast'
      preLoaderRoute: typeof PanelProcessingsIdProcessingsForecastLazyImport
      parentRoute: typeof PanelProcessingsIdProcessingsImport
    }
    '/_panel/processings/$id/_processings/graph': {
      id: '/_panel/processings/$id/_processings/graph'
      path: '/graph'
      fullPath: '/processings/$id/graph'
      preLoaderRoute: typeof PanelProcessingsIdProcessingsGraphLazyImport
      parentRoute: typeof PanelProcessingsIdProcessingsImport
    }
    '/_panel/processings/$id/_processings/upload': {
      id: '/_panel/processings/$id/_processings/upload'
      path: '/upload'
      fullPath: '/processings/$id/upload'
      preLoaderRoute: typeof PanelProcessingsIdProcessingsUploadLazyImport
      parentRoute: typeof PanelProcessingsIdProcessingsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PanelRoute: PanelRoute.addChildren({
    PanelProcessingsIndexLazyRoute,
    PanelProcessingsIdRoute: PanelProcessingsIdRoute.addChildren({
      PanelProcessingsIdProcessingsRoute:
        PanelProcessingsIdProcessingsRoute.addChildren({
          PanelProcessingsIdProcessingsDistributionLazyRoute,
          PanelProcessingsIdProcessingsForecastLazyRoute,
          PanelProcessingsIdProcessingsGraphLazyRoute,
          PanelProcessingsIdProcessingsUploadLazyRoute,
        }),
    }),
  }),
  AuthSignInLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_panel",
        "/auth/sign-in"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_panel": {
      "filePath": "_panel.tsx",
      "children": [
        "/_panel/processings/",
        "/_panel/processings/$id"
      ]
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.lazy.tsx"
    },
    "/_panel/processings/": {
      "filePath": "_panel/processings/index.lazy.tsx",
      "parent": "/_panel"
    },
    "/_panel/processings/$id": {
      "filePath": "_panel/processings/$id",
      "parent": "/_panel",
      "children": [
        "/_panel/processings/$id/_processings"
      ]
    },
    "/_panel/processings/$id/_processings": {
      "filePath": "_panel/processings/$id/_processings.tsx",
      "parent": "/_panel/processings/$id",
      "children": [
        "/_panel/processings/$id/_processings/distribution",
        "/_panel/processings/$id/_processings/forecast",
        "/_panel/processings/$id/_processings/graph",
        "/_panel/processings/$id/_processings/upload"
      ]
    },
    "/_panel/processings/$id/_processings/distribution": {
      "filePath": "_panel/processings/$id/_processings/distribution.lazy.tsx",
      "parent": "/_panel/processings/$id/_processings"
    },
    "/_panel/processings/$id/_processings/forecast": {
      "filePath": "_panel/processings/$id/_processings/forecast.lazy.tsx",
      "parent": "/_panel/processings/$id/_processings"
    },
    "/_panel/processings/$id/_processings/graph": {
      "filePath": "_panel/processings/$id/_processings/graph.lazy.tsx",
      "parent": "/_panel/processings/$id/_processings"
    },
    "/_panel/processings/$id/_processings/upload": {
      "filePath": "_panel/processings/$id/_processings/upload.lazy.tsx",
      "parent": "/_panel/processings/$id/_processings"
    }
  }
}
ROUTE_MANIFEST_END */
