/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PanelLayoutImport } from './routes/panel/_layout'

// Create Virtual Routes

const PanelImport = createFileRoute('/panel')()
const PanelIndexLazyImport = createFileRoute('/panel/')()
const AuthIndexLazyImport = createFileRoute('/auth/')()

// Create/Update Routes

const PanelRoute = PanelImport.update({
  path: '/panel',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PanelIndexLazyRoute = PanelIndexLazyImport.update({
  path: '/',
  getParentRoute: () => PanelRoute,
} as any).lazy(() => import('./routes/panel/index.lazy').then((d) => d.Route))

const AuthIndexLazyRoute = AuthIndexLazyImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/index.lazy').then((d) => d.Route))

const PanelLayoutRoute = PanelLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => PanelRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelImport
      parentRoute: typeof rootRoute
    }
    '/panel/_layout': {
      id: '/panel/_layout'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelLayoutImport
      parentRoute: typeof PanelRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexLazyImport
      parentRoute: typeof PanelImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PanelRoute: PanelRoute.addChildren({ PanelIndexLazyRoute }),
  AuthIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/panel",
        "/auth/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/panel": {
      "filePath": "panel",
      "children": [
        "/panel/_layout",
        "/panel/"
      ]
    },
    "/panel/_layout": {
      "filePath": "panel/_layout.tsx",
      "parent": "/panel"
    },
    "/auth/": {
      "filePath": "auth/index.lazy.tsx"
    },
    "/panel/": {
      "filePath": "panel/index.lazy.tsx",
      "parent": "/panel"
    }
  }
}
ROUTE_MANIFEST_END */
