apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-certificate
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nerlihmax@yandex.ru
    privateKeySecretRef:
      name: zakupai.letsencrypt.key.tls
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik