version: '3'

services:
  caddy:
    build: ./caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data

  api:
    build:
      context: .
      dockerfile: dockerfile
      target: api
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}

  web:
    build:
      context: .
      dockerfile: dockerfile
      target: web

  geesefs:
    build: ./geesefs
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

volumes:
  caddy_data:
