version: '3'

services:
  caddy:
    build: ./caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data

  api:
    build:
      context: .
      dockerfile: dockerfile
      target: api
    ports:
      - 3000:3000
    environment:
      - PORT=3000

  web:
    build:
      context: .
      dockerfile: dockerfile
      target: web
    ports:
      - 4000:80

  geesefs:
    build: ./geesefs

volumes:
  caddy_data:
