FROM ubuntu:focal

WORKDIR /app

RUN apt-get update && apt-get install -y wget fuse
RUN wget https://github.com/yandex-cloud/geesefs/releases/latest/download/geesefs-linux-amd64 && chmod a+x geesefs-linux-amd64
RUN mkdir -p /mnt/bucket

CMD nohup ./geesefs-linux-amd64 zakupai /mnt/bucket
