FROM node:22.10.0-bookworm as build

WORKDIR /opt/app

COPY web/package.json web/package-lock.json web/.npmrc ./

RUN npm ci

COPY web .

RUN npm run build

FROM nginx:1.27.4-bookworm

COPY --from=build /opt/app/dist /usr/share/nginx/html

EXPOSE 80