apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: api-run-migrations
          image: cr.yandex/crphumdkkpdrgg386glu/api:latest
          command: ['alembic', 'upgrade', 'head']
          env: &envs
            - name: METABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: dsn
            - name: TG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-secret
                  key: token
            - name: TG_WEBHOOK_URL
              value: https://api.xn----7sbbznd9a5a.xn--p1ai/tg/webhook
      containers:
      - name: api
        image: cr.yandex/crphumdkkpdrgg386glu/api:latest
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
        ports:
        - containerPort: 80
        env: *envs