kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-admin-role
  namespace: zakupai-schedulers
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-admin-role
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: full-admin-sa
  namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-admin-binding
  namespace: zakupai-schedulers
subjects:
- kind: ServiceAccount
  name: full-admin-sa
  namespace: default
roleRef:
  kind: Role
  name: full-admin-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-admin-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: full-admin-sa
  namespace: default
roleRef:
  kind: Role
  name: full-admin-role
  apiGroup: rbac.authorization.k8s.io