FROM python:3.12-bookworm

WORKDIR /opt/app

COPY api/requirements.txt .
RUN python3 -m pip install -r requirements.txt

COPY api .

EXPOSE 80
CMD [ "fastapi", "run", "main.py", "--proxy-headers", "--port", "80" ]