FROM python:3.12-bookworm

WORKDIR /opt/app

COPY api/requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt --root-user-action

COPY api .

EXPOSE 80
CMD [ "fastapi", "run", "main.py", "--proxy-headers", "--port", "80" ]