/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export type EmailNotificationChannelSchema = {
  /**
   * @default email
   */
  type?: string;
  email: string;
};

export type HTTPValidationError = {
  detail?: ValidationError[];
};

export type JoinSequenceDataInfoDto = {
  left_join_table: string;
  right_join_table: string;
};

export type TableFilterFrontDto = {
  table: string;
  type: string;
  column: string;
  is_array: boolean;
};

export type TableJoinDescription = {
  base_table: string;
  join_sequence: JoinSequenceDataInfoDto[];
};

export type TelegramNotificationChannelSchema = {
  /**
   * @default telegram
   */
  type?: string;
  user_id: string;
};

export type ValidationError = {
  loc: (string | number)[];
  msg: string;
  type: string;
};
