"""init

Revision ID: 1031f9031a37
Revises: 
Create Date: 2025-02-28 19:34:35.109652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1031f9031a37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificationchannels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_chat_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.CheckConstraint('(tg_chat_id IS NULL) != (email IS NULL)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificationchannels')
    # ### end Alembic commands ###
