"""unique notification channels

Revision ID: b12001df7262
Revises: c21237328661
Create Date: 2025-03-01 09:41:17.959170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12001df7262'
down_revision: Union[str, None] = 'c21237328661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'notificationchannels', ['tg_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notificationchannels', type_='unique')
    # ### end Alembic commands ###
