"""add tg user

Revision ID: c21237328661
Revises: 1031f9031a37
Create Date: 2025-03-01 09:02:13.825622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21237328661'
down_revision: Union[str, None] = '1031f9031a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificationchannels', sa.Column('tg_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notificationchannels', 'tg_id')
    # ### end Alembic commands ###
