name: Charts

on:
  push:
    branches:
      - main
    paths:
      - charts/**
      - .github/workflows/charts.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.3.0
      - run: |
          mkdir -p ~/.kube
          echo $KUBE_CONFIG | base64 -d > ~/.kube/config
          kubectl config use-context zakupai
          kubectl cluster-info
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Release Clickhouse
        run:
          helm upgrade -i -f charts/clickhouse/values.yaml clickhouse oci://registry-1.docker.io/bitnamicharts/clickhouse

      - name: Release Postgres
        run:
          helm upgrade -i -f charts/postgres/values.yaml postgres oci://registry-1.docker.io/bitnamicharts/postgresql