name: Screenshooter

on:
  push:
    branches:
      - main
    paths:
      - screenshooter/**
      - .github/workflows/screenshooter.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          file: ./api/docker/dockerfile
          context: .
          push: true
          tags: cr.yandex/crphumdkkpdrgg386glu/screenshooter:latest
      