name: Web

on:
  push:
    branches:
      - main
    paths:
      - web/**

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          file: ./web/docker/dockerfile
          context: .
          push: true
          tags: cr.yandex/crphumdkkpdrgg386glu/web:latest

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - build
    
    steps:
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          KUBE_CONTEXT: zakupai
        with:
          args: apply -f web/.kube