apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pg-us-claim0
  name: pg-us-claim0
  namespace: datalens
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
